helmCharts:
  - name: qbittorrent
    repo: https://charts.gabe565.com
    version: 0.4.1
    releaseName: qbittorrent
    namespace: media
    valuesFile: values.yaml

resources:
  - config-pvc.yaml

generatorOptions:
  disableNameSuffixHash: true

components:
  - ../../../components/tls-ingress

configMapGenerator:
  - name: tls-config-qbittorrent
    literals:
      - host=qbittorrent.nora
      - service=qbittorrent
      - port=http
      - pathType=Prefix