helmCharts:
  - name: qbittorrent
    repo: https://charts.gabe565.com
    version: 0.4.1
    releaseName: qbittorrent
    namespace: media
    valuesFile: values.yaml

resources:
  - config-pvc.yaml

patches:
  - path: gluetun-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: qbittorrent