---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arc-pat
  namespace: github-actions-runners-myzopotamia
spec:
  encryptedData:
    github_token: AgBTMNVYnYTrR5ZosKRTKmKjhc6r8GelMe/okLN6jm4xHlp9j4EuVmiNPU/kmqO0NPyuJLUDKPdJobExNRwDuOVS82jK1XnZ6o+dlocD0yERZ6N5WTp6ZhYbIKRwfix/enV/tB0RXwXPojy6rG9jHY3O9wLEJGT+EPK5mDeEXV2VPh776QFgjYJqO5J1c9p8tX52zv0Jpi9EQ1BNgV4coUOIfzyke3k2hT85SCI2vZMAF0duUtEVnv8OFvbSsHa8iPz5iC1Ew5TkTti0p81V46AO/RALJEgAyEyVJNMGSJ53oR8j0R8MNz0cJYiB/IGSZpQXZ7oKbcXScg3qiV/aRC2lGHSvvwyBL5Kv/ah+FWgTp0ndXdIFRmkzxNgrIyAWwkjzOVfonLtlQtDk+vqD4WC1/4lnSxsnvAvQUHVABLrEyDGqXD1s/2D8kPFD1YIW4bssupRDbW44xdZuy3UhCgKXw7Mpwl0MnHNJ4RM48M7VkvjcWlzZdrKOauO80Jshmo539JtK2FNY9iPjGK+V69/bqHMgOzoR1TBP6ETAhXf6HNBw4wLG6AO8OJxXY2I2Lqx9fKTzKb/C6yC+GAfQcdMMaIwR6LJfZ32xAQj5ugZxeZZs7GxgwAHj+hDzi6Hc8w3LGMoIYRJxsJ/xR30JKJp6pmLtfqH/NCMBy9Gji7+VDAB+SU4HzsuOy5+UrPsAo4GunjcEIo81eYSS/T9L4Ai2+ZhWk+9ezvmTysMm9yJRfMrsbH6InGoV
  template:
    metadata:
      creationTimestamp: null
      name: arc-pat
      namespace: github-actions-runners-myzopotamia
    type: Opaque
