---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: seafile
spec:
  encryptedData:
    rootPassword: AgAvJDmDpR17DMZjrB6Jomugt/buR895LyhxRCmFjKr2XtuowCdITOLTTHeli5IqYh9RDWgLoiNPjkw3NrppJbVYNLdBkZpsmbGOsV/rJyz0BIgy17UlPhBr2YOHupa9wfHdjXYQDgLJmMxgY7oQQpxV6iCoTkDsnkAyvQK6wKxP+p7R0765BHeFtFr8DAeYwqA0LgxQykE3URao4E9SBoCqK2pYtXKwaqAiWe2lWBsDbAuChODrrn97D1YMMi4QrPrc3UwXpVLmu/utUnmUeD4RqpXyUpkPCs6uYq7e5+KNFyyBMnZDSKP/OgOsEEUzpEyhaGlEd5cDBCNdgEteXmD87OtwTUAmIxUr2FSnnlHlJErZSVTiB/K0nkAlcp5JVhpKIfbuxgCfQEzMeEp/U3/vLkSUOM+1/ItBgoL63uLVIL+10+8n7afCWv3DxX6SNeJ9oZiPwBsFNOV0pmbox2CJeHzZ4MyWd1s39D+CLR6VmpjpdsR9dPBHyjcuejKK46oYb0MMHdaT2RRLzpaiTwBmBxjm77PBXBF0hSMrbd1Pti177+X/GhNKxr0CznufNNeyI0kNaCgteVuV5Q1/lJs4manw5sFuK0ZVcTrgXnTaJt/CcB9KKfWmxGfFqq3Y2gQVX2acz5YhV36yVqygaeBx6+OJvUgEy/tja1XMH1ru8t0TYpKIwc7X14Kn4MGK6xhfg6Xbm75sYEgjfXdvuMw8fqNg8A==
    userPassword: AgC8gkStiJDHrH60m2vH9Yil+L8y5FHJHKtDkWuiVlLUvvvdEw2QyO8ukzYMSutXl9VBoOTv3eIIZDcNCSdwEtjeHnu6CsrM7GiCzAg6TJ6zLmIXOw67Euy9K+EoGR3jEnvP29sikPgOYctr+e83gNjCNXjIkNKMDF0ZxwLGcpAu2PTZB5watV/ni+9mrhitKya+FycJ/O8Rub79ZTCKMi+jM2dtqzpX+oS23q02XFVL7A/Fc5ChcBQCqvxlTDA074xbasbiTfTlK5YtnSWT5RL92AR9axlCH/gboq6VPwDESIkIZ+lmMVdpaVBG+vQ9oF8DvCknpnXVnawe5fCC/DgVUsw1hUH2X0KXZdG13XjkuPcrMETg7KZnIRxK43E8fsoipEO0VCyN2BLAAO8ElwDIei+NwXgIlK/433SjkC6YzqqjyIS0fIhSOPhO+RhWa3ANhWt/ZpbyZK/SWu6YfVH+ymUfqBJM7hkpJo4dq56+fpv/nT2kUX8cKgYdwN2T0ruL+/V6PbTC+zYz33+Zk/bs0QE7Yl2A3yIsXahXYKgvXgeoiyPVl1dYgXzyV1DBF6+HQrIPJPSxbcwA8eWCCkN02DlqZ0oDtsbPm7tpw7gMvTbCuXwsmCemUVlKv8NX5VdTTTOT78K8MSr74WQwe4uqiZ7csEzVeKIEap8IE0i3KhSRS8/oWHrWmosBumdWgr5KLGU8kSCvY1hyRBo2iOqN
  template:
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: seafile
    type: Opaque
