---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: ether-docs
spec:
  encryptedData:
    .dockerconfigjson: AgCQ9blOdFcdEPKcfBhx2gno95kjcJFGiDae0v6UW106cvVo8aF5VmVkmY+EP9UPX2tTV/9fENUCT7EhgndzRqdxmqBTbo5Jp9L35IsQ79NAUcLJVUOaQ4bzZfR4otycE7c20NcB7o8pgd6t3/ham/hAY18VoOTzslhWScHify1ZSZze8k9gscPW/V9jqDubzbePuN6yoe0zAY34u1TfYZfaRV3Xno+KgBdYVcNuMoehWjxDjtCTIASX6LmMbNjZ445yixHTVo/MfZZXNBwZeqdFTxdEIOjXUc19QWbRl/H9VZwPqqLobKZfVNzcVyX7TsZO+go+SeOlPluK7s/oJcWGBi5mQyLAj7uQ50Q1Dx+NVK3ZFyK/QvTWTv4w2cvG+XVIGZxGNEzEKXOkGODBR/WatFMM7nJuPTc+ttKLmzVcoiUVwIL8sMDNbmz1yaJAZYdO6yJBnKfV+1QCgyPEiTTQJ4GTFZcJBCs96RESnC9qqbDKisXTKj8rIIoYXtzezffp/gz4iSonQx00mZ1iteNFfBHu+dc4qAxwVg/UoMLQvWawiP6JPnXyG/OBbP+ZJTiB6S/46n3ph3vGtjEX9BwvLs0pbNqF1is009t/wbPbV0hnUSjYNpmjE7ErPfIuBFpZY/sHzpnabb23G01v8rmFgcvmPVm8ZQTMB9sPftsiJUoJY5pIWVom+EMrfi1a0+F3kZwgnDRv6fsbm3odbcZ5ynlfhIN1pAewkS3dqRu5wR1j17LSZZSaYdrlrDQqQaI3PRwp1QcT4N/Ps5B9ZpNhSmfySWbrLHlXxkA3Bt07D6wCCWoivCHUTQnX5ypqOuG8VW8+nuAwlYIHtDzK0+EmFHg2aB+080fqwUjfWkDERbom1TwzTUxvRD9l7I78NeApNDsNyfUkNkrQxaW/d+WO95odRdmIUPClKJuQ3cOFvQ==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: ether-docs
    type: kubernetes.io/dockerconfigjson
