deploymentStrategy:
  type: Recreate

nodeSelector:
  kubernetes.io/hostname: ethernode-gmk

jellyfin:
  enableDLNA: false
  env:
    - name: TZ
      value: Europe/Warsaw
    - name: JELLYFIN_PublishedServerUrl
      value: "https://jellyfin.nora"
    - name: JELLYFIN_CACHE_DIR
      value: /cache

persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: longhorn

  media:
    enabled: true
    type: pvc
    existingClaim: media-center-data

  cache:
    enabled: false

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    memory: 4Gi

securityContext:
  privileged: true

podSecurityContext:
  supplementalGroups:
    - 992

volumes:
  - name: render-device
    hostPath:
      path: /dev/dri/renderD128
      type: CharDevice

volumeMounts:
  - name: render-device
    mountPath: /dev/dri/renderD128