apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-center-tls
  namespace: media
spec:
  secretName: media-center-tls
  issuerRef:
    kind: ClusterIssuer
    name: nora-ca
  dnsNames:
    - "*.media.nora"