namespace: media

resources:
  - storage.yaml
  - prowlarr
  - sonarr
  - qbittorrent
  - jellyfin
  - seerr
  - certificate.yaml
  - ingress.yaml


# TODO:
# - Backup Jellyfin config?
# - Backup Sonarr/Prowlarr/QBitTorrent configs?
# - Add normal http for Jellyfin for TV integration
# - Add everything to Homepage
# - Add 1337x torrent tracker
# - Bazarr for eng substitles?
# - Maintainerr?
# - Add Radarr
# - Make sure this all works properly
# - Need to automate some setup? (creating folders, giving permissions, etc?)