namespace: media

resources:
  - storage.yaml
  - prowlarr
  - sonar
  - jellyfin


# TODO:
# - Retain Jellyfin
# - Backup Jellyfin config?
# - Retain media storage
# - Backup Sonarr and Prowlarr configs?
# - Ingress for Sonarr/Prowlarr
# - Add normal http for Jellyfin for TV integration
