namespace: media

resources:
  - storage.yaml
  - prowlarr
  - flaresolverr
  - sonarr
  - radarr
  - qbittorrent
  - jellyfin
  - seerr
  - certificate.yaml
  - ingress.yaml
  - secret_vpn.sealed.yaml
  - gluetun-proxy.yaml


# TODO:
# - Backup Jellyfin config?
# - Backup Sonarr/Prowlarr/QBitTorrent configs?
# - Bazarr for eng substitles?
# - Maintainerr?
# - Make sure this all works properly
# - Need to automate some setup? (creating folders, giving permissions, etc?)
# - Fix Bleach?