apiVersion: v1
kind: PersistentVolume
metadata:
  name: qnap-media-pv
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  storageClassName: ""
  mountOptions:
    - nfsvers=4
  capacity:
    storage: 7000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.185
    path: /media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-center-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7000Gi
  volumeName: qnap-media-pv
