fullnameOverride: radarr

controller:
  replicas: 1
  strategy: Recreate

image:
  repository: ghcr.io/home-operations/radarr
  tag:
  pullPolicy: IfNotPresent

env:
  TZ: Europe/Warsaw

service:
  main:
    type: ClusterIP
    ports:
      http:
        port: 7878
        protocol: TCP

persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: radarr-config
    mountPath: /config

  data:
    enabled: true
    type: pvc
    existingClaim: media-center-data
    mountPath: /data

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 256Mi

  limits:
    memory: 1Gi

metrics:
  enabled: false