---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arc-pat
  namespace: github-actions-runners-edgar
spec:
  encryptedData:
    github_token: AgB5OLcmFCiXSas4RJYIpeJ2l2rsY8cDNSGJNlZFzIGJ4y20XIzUZUv57bRQtTEyKss3M8zKgYDX/xeq4gYfR+SLev7gf+Y7JxW4YHbtyba6UeaVNBWPss0C6D5iNAvIeZJV0u7xxAjWxTK8TAm76rbHlF2Y/qUbPmVnXK/plVfuMdwHJNqZMc4qUL99v1dlL3FsEHJvSn9Z8Q8cdos4MrSqOKy/15VLNq1n977m1mwBH3/hQTSLINCWIt896R1Aq6nb5C+AIQ3zeZnqwqGHupvg0i103lwQnrtowqbdiX9xttIQIR7lYVbE0YWlp/zFuoV0Ch0Frorg8RjsEJQBQmXFM8B4cEsiEtnCYBvofjvibKdmf1iYCWu/wNKmWJksczyGYtr6e6OQrV3ChKYF/s5VTCCT9SDfEwchwGY4+S/2zDcm2WTphLzJsFjdTM151pRcpdu7SibDkRYasB82y51g9N6q731LCERZ1ZkWoHXfofRdokdWjtmxulWH3e6/34p50Zzc4eejQ57bLLX4bFdffatY38ClBkGsnRFZYYC5C3L+dCtfX/crFhoVoJHXA2mV0br22dCd05np6W2FS4fCMDCGB6fXosmO7EWt8duzz/YuWRy4sAT1LG4vaPl2gnv6toyzb/WevSvHOkYp2xod/gBieOIL+XCDI5gwXUzqjsRr8+vAwjKwFRsZlHunEmi9APhuxx2qM9SIrSAZHE4garFZoJs8DUSHapSt8OdoYQNDHobm7rN5
  template:
    metadata:
      creationTimestamp: null
      name: arc-pat
      namespace: github-actions-runners-edgar
    type: Opaque
