---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ntfy-auth
  namespace: default
spec:
  encryptedData:
    NTFY_TOKEN: AgBvlNRC8qCjzt/EjH6mdej+9GrGU7dYeo5YgRYADNfC+vOmq5SSRr8XZs62B4kcl/Vp7+gmtHYPdCTUYwh3/QVUqsCCSZ7JAHmygYTkT2ZrzJnT7j8WwJD5E35xPHgvLEvpY7N4tHzk+BW75+sXVtHqO+hHsb8axwSxAlJdhdsbQHOIFJby6Sh8wNQeU2s5CnNND2BFPspMPPm3ld7oHR9YaPLPX4nMr048tOsicMAj17NcxOwKaiwCxf1WJ9DhjtSZUU+dRJFaVyKm7FrWMvYLNaMHRCmQi72enYqGastsxzPlpt04kOxE3s866/GEUkV1Gr8+rp7+pc8C1LcblkW5WXPq5KYZLvSlXxhLu43qcuebL1mIumQCk9ZGgInZJKU70Uz84C55CFRQYK83O10SSREOCLpHjjqiHnlxgJTeTXdAKKq4lBYa7rsq22kWnkRqJCKl3ALA0v2GnC4HEvjny19NeRGM8DUo22GsgNm7WA8nfPWtYiswsKL9ZtSubMkX+uXlQFZU0nhijIr9ErMOmbj0D6h0Yx0xWFocz3oL7mRhF0Rt+XjEwPQJHhZMVCdWXOac5jjy2j3ILXySCMlczGTddJ1AwkJ2y5HLX2C6sYVH2MZofZtqFxaB7b1A+d5PRZ8GEn6BT5M4O+St487xKWKkybaYVLR+w+eSD6xqkB5kv5io+3fkIOVccAnA0FM7heAQe/nfaTECgvw847TeTkz93m0Q+xbg1BQh7At+Ww==
  template:
    metadata:
      creationTimestamp: null
      name: ntfy-auth
      namespace: default
    type: Opaque
