---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ntfy-auth
spec:
  encryptedData:
    NTFY_TOKEN: AgAXFghnDvVudAV4cAqXr/OrtsVblp5LQc/kmMHSRWH2OIwfSder2O/xjSnEeC8EZNfc7QuFCfYMYrup4kQp1AtFjkwDjeaeWAhu4IBxW7ozCTOhemg4Xz9uublQhEbrpDhh3ZFS7eVf04Wkh0HIHwAAxwldhRC1a/FTVckgvqRorlY4siu7UVGEy42md0AQsOPkIdJUAcaVcAXD30A+js9qxZ9a+XA9FFvQkPUoXjczdAT4bDYoYEpsUr0d1z43clPloP7kl9MReCfwQzMskphzzZQtDuYeyxUcsJlOiKQB7u0VdcQd2hqp9WG6uvIvoF7BbBbDHkELO90iYmm2Xpegn/5t79qXfw9yP1keSF9XcJ6ipMhQfoKtTAHcoyJNMn2W1aRqeD4yjJ9xpWNbn0A8pIvqbkV6PnQ+IkqEYGR1n1JohbrrvPwdx0wjFToHJr+QZIJ25c8nJ0/Qfzljbk/lv3kzfYv6qIKWjrL+EaBW08yIvkbQOobs4FLs2m7j3w6MS28mcy++HoWTuPCvNAMRP3NYKD4zWTIjPqVSGmP7qbh27ad3GFxIzLvVx2MqfoWR0Pf/LP/SxJnlIo4tJ0gqHy+QOk/ciXrCr4W0V473dalFoshzB8msaGWeXaR8rh797zEU99ystcJOUXTJrK05C77PuGmd7lEYFF//FCdd58fg1Gjmh3EsBYduHaQbSB7hijfgUWEYQtx7BVzwLE9626Wt9frgQXIo9p5VDYeQTA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ntfy-auth
    type: Opaque
