apiVersion: v1
kind: ConfigMap
metadata:
  name: envvars
  namespace: edgar
data:
  TASKS_TEST_DRIVER_LICENSE_N8N_URL: http://n8n.n8n.svc.cluster.local
  TASKS_TEST_DRIVER_LICENSE_N8N_WEBHOOK_PATH: "/webhook/driver-license-response"
  # LOGGING_LEVEL_ROOT: DEBUG
