apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-actions-runners-acolyte
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/rskupnik/grimoire.git
    targetRevision: HEAD
    path: apps/github-actions/runners/acolyte
  destination:
    server: https://kubernetes.default.svc
    namespace: github-actions-runners-acolyte
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
