---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arc-pat
  namespace: github-actions-runners-acolyte
spec:
  encryptedData:
    github_token: AgCCCVTMnrHwQ1r+hHHt2wQV8K8xLormhm5cB28v8WEn3q4IafVMdB3ziMJIimThdgM0GCaIva1wK+ueAjBnqMGSKcbSBfHutQnWme5F7KzbjskwsQMaZDzWuTlwvORK8hThooSEdjuQL1LngxHq8xuYAIapkjtVcxlyyYTMCRudcE6eRRbVWVb+w3zpW2r9jJFHahQzpK6IpOSxwBJx48dfSzYkjusJtZIkR3yB5TMVgu0q+7PekDQz9KSnVdLURLy7QrCMIwrRG1SP1R2q+VUm3BSiRmITESqAOz/3M5sRIWJ6umltqaOhypOpFJcrkCHx6tKb33XAlgI3gBllZ3Py6badnTPgcoKjraVM/E3ume8bB3TRegXuxCGsCHUyACK1T+0VMz8moyjWu9eeDL/g9U71iTA+CBd028/Nxrw/91c7u19OV15gdeUOGEerBKz2bAS18HCE+A2RPc/LxgTM5sBwK0THYuYiKnpTAt5oiG/jFUg4MrBDkmf3IpkgqPOdpfuDhAGDs3WRjjlefA932TLAXrMO47Yy6kueGFTKm1Xh2W0/kcgorRPXx2sTVjmprLcbjsDmqpEemyp+6JEyT06Dp8hmHQWaUclbHToWU/Y9DiqahawXRraWspTIUUeCkugrK5Z6Ja5inomqy4XASLihCGC6KgSPLyR0K70YMfcjJMuRfCD0n54BigvX50UzNf++IidkGJjrcTBm/e3WsFwMsfm0Z218lk9slrDYG1b9QHzxVimX
  template:
    metadata:
      creationTimestamp: null
      name: arc-pat
      namespace: github-actions-runners-acolyte
    type: Opaque
