---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-credentials
  namespace: seafile
spec:
  encryptedData:
    password: AgCQRM2iyEJgGMLemeQGUiCzNxEyZeD7MT74BnOSgQcqBjOQBqECyEQasivxTzuA4c4/jBPWHJM4NobfYiqIv5eBWaknMupuHGy/ijB50dyL9hT3qROp+0noQr+GTbUGKmeTjYKI4Srxk4La/8LgPIjdtYKvBmai+lrhG9gTSsSguwo14czHtLY5soRNw80N3akne4y1YhZhDMIvi+awac6SIkMt087gNqjErsZyZ8UdUe7tIlq/c7+7PNiNNd85q6NRYMXjWM/vcbh1zC6bldLg3UdyCVKQcl4c1TvrBWbPcyLd7FpkU04sAP78KqnwJR7SPjWj/4RpJoFt0ShQ4G41ABhsA5MyV8yLdThZ7utSvxOtkYmPBckkNZtRUGk2DaKSVjVy6yTzckB0xogN0LBTgp9QkTfIkz6KyBeXDaGT43+eRRmEN6ZZP1pbXk/oKSIUj0dHOY/yS0jq3Z80Ti1z67nuSxx46vZDz/wkq6EQw3Uq/sto8TCMYOu+IdbOyWW35G9L1vLwSs4VsN7GyRu62fSz2eOwQQMl0049cpHqR0M7LsVeUo3Qt1NZoOxGwWUBVbFkaADLtKVrtjeNy1vh3HC1X9bmSuhjUQ8AC3zqG+JWTvFeqkXKa0Anyk4vaGwyy7b5fsb4D7qH92AbAHDLaCuZRSLMqWpQQmshVqSATzjj3/xfRtc3cGpChPMrjj+KzNoBUspeo1ro358pmSkj
  template:
    metadata:
      creationTimestamp: null
      name: postgres-credentials
      namespace: seafile
    type: Opaque
