apiVersion: batch/v1
kind: CronJob
metadata:
  name: nas-backup
  namespace: nas-backup
spec:
  schedule: "20 1 * * *"
  
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: nas-backup
        spec:
          restartPolicy: Never
          containers:
            - name: backup
              image: alpine:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "Install rsync"
                  apk add --no-cache rsync openssh-client
                  apk add --no-cache rsync curl

                  echo "Ensuring target directory exists..."
                  ssh -i /offsite-ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
                    pi@192.168.178.69 "mkdir -p /mnt/backup/data/"
                  
                  echo "Starting backup of folder wesele..."
                  rsync -avh --delete \
                    -e "ssh -i /offsite-ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
                    /data/wesele/ \
                    pi@192.168.178.69:/mnt/backup/data/wesele/
                  
                  curl \
                    -H "Authorization: Bearer $NTFY_TOKEN" \
                    -H "Priority: min" -H "Tags: white_check_mark" \
                    -d "Backup of critical NAS data successful" \
                    --insecure \
                    https://ntfy.nora/backups

                  echo "Backup completed."
              volumeMounts:
                - name: nas-data
                  mountPath: /data
                # - name: ssh-key
                #   mountPath: /ssh
          volumes:
            - name: nas-data
              persistentVolumeClaim:
                claimName: public-data-nas
            # - name: ssh-key
            #   secret:
            #     secretName: nas-backup-ssh-key
            #     defaultMode: 0600
