---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ntfy-auth
  namespace: nas-backup
spec:
  encryptedData:
    NTFY_TOKEN: AgCZ16m6RMnWvjCPmXKXYiIPYC3uEjCf82naM4HGwruXdonckxVg8ci8udoOLmVToQmMbvj4VZLkJpO56JpNrJCVnwuAFImpMmGGsCQOI8M0UTKtcO84tu/PfvppAZOPi76yoMl8RKhXmUvSoIPeaGygo3Af1oLwe4ThgRpGE+jkP4g2/EiBzAHJF8+5H+s6MQxmOjRFFTkJfxPFcImNM08fgIdnis5crqSkKWYGTr1y50F4T6ffRZh5XQ0yltwGWKESlWJ0LNyVlWt9w4eVjIek4vAN80kpktWvHgjbMwCcipYl9Y3tx1a9vOGlvlZWH5tZ9F9kcrXHqY0JcODVYuADOY8LpnMn9e8EMaZr3P6s3PdW9kV8iUpr3grVeR6Su7hHiz2wy40JHyiDAVEi5Uu/hxU9Q2MnSdyR8DayeTI7bThb2Y56Kt099Fn83jYGt3CS2pyAZ5bz3JiqUTUphEiKmHvR2Jk3rW5EtFCUXczieKdRAJdCI9UvO4e0CbWuQHl/kkIu5ggc8BtjuLyJ0vxp6fghcEB6+uDyUBAACQMvVx9K6GfAeZekZZvONOIn2dYjE5NPlrOHdwXnnjRp/TAp1DUBrBmy66JGnLw6dGdlt/eKL0QfXpG0Mru1Lq+8+VvaI9yjhhflYP4qMR/KNh36kTZuu1etB8AzFZEEF744tZiWwOl3Vn435jShGRQndHI2faAuFVW51EFgLfm8gXZqvspEYpzRQW5tS1+VtNG3cQ==
  template:
    metadata:
      creationTimestamp: null
      name: ntfy-auth
      namespace: nas-backup
    type: Opaque
