apiVersion: v1
kind: PersistentVolume
metadata:
  name: qnap-public-pv
spec:
  storageClassName: ""
  mountOptions:
    - nfsvers=4
  capacity:
    storage: 7000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.185
    path: /Public
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-data-nas
  namespace: nas-backup
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7000Gi
  volumeName: qnap-public-pv
