---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: llm
spec:
  encryptedData:
    redis: AgACn9IGTzC04rZxtXtGibSPBe4kXWvXdG9CTCwleiKfLpu2oHjgfCUfiJeX5ESVRuHFo+GFCiwI8jzZIHazSBo13rE0Ik2rmqGRH/i5dLLsIoKaudnyNV3OeuY/iWkjYqB9VaNJvZ7//IvYk1roMydDG3O8CAK3m0ywP/WuQVz/uqw684YhYhpf+RdvOODCa5blGPKDxPV70UpgiXA2GtTpmlAKAJ8+lg4OiYzW3IaqhGgDBCSTXl03Sw5CIbmXiCJ3W07RTwjILBmx1z+RzW9kwokKi8mpNnqns+3KU21IHx9OJBIn6KlSmXKFv1+O8xFV8iIh9C9R0bYWSfI0rmTsWoAyyMJF+A5abtT256is9rdfrkMqf5ZIAz6EFLTNTsC2J9meMo2kgp0j2lFO5c4D/Zjsmg4hhmLd0rsszy+1ScIOCkr9y2oU0TR1+n7QC+cWIhZohi9oEsLA8fBvo51VNkP0o+LgFY5NGsys5DJLWsLpmjwcYPdBU6SS5DOjt0K8l/V15CgyE6puxGrIycjb6XD6HSPHpbkB7h0gvvTocURWPYaxYWPrfjqzBUW26ucHvutad+VD+4iPnwx131koRvW+ehwau+Jb2rd/EjyAKwpQ0ntMr7BhsIGtgGPb0Ht9zb9dvC/d5TLc+YhrzpNEvtEgND9ViH+Cj2YispSbINyO1+gEou0n57iqA0pzMJp2xaPA4PKn8nIkH35FWkj7
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: llm
    type: Opaque
