---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-oidc-secrets
  namespace: argocd
spec:
  encryptedData:
    client-secret: AgBWi2habETWtAUwM+pVTEqNHCVpT1Ksk8+4Bpmz8CDZDZUtOglXxSLannf2h2hdtOUDAfVpFvjhNmzsjk5EVrUbYgMb3HgM+r9DBGx6nqE4qOSM92bdxwTupzQfZy+16d/zhx2OIdHSG3gOr4gIHRf7DEW9wxpPjyUfGuADGa0rkYteov+DN9hlc2GIyUahQmDzyrpVzY53B5KuyXEWFt0g0XxCFIz/cBICM0HnoSdVJ4351mjZNAiuA2fYTOByFt3RExY+38ZxfoAs2Ua3Bued8BhbtN63cDhxxpSbBYw9FqOAGv0Qoa6xEtAf5T+oPWXeGiBgNAFrD3axXfILCN9321LD8JSwOG4Mwhe6/0Rvp1+0XQtIbGv/CyzWfWWE5uK4xNaXvAtn1862LRVSsR42gXuC8+uznxQnLinMs8tInWdshLSamzLW4Cwx38P1vXMQ9ZWYieiSYk8teDY6DnEMfLAV8t73klD30Ht+vQXuFNXHR0VTzncCVqYPNKC8UF9rGVbPJHRv/X0Nvr6pY152g92fsuCKOGgIzGi3C8K47uMaLubV48qliUihmUcWjgaldh37rqk2es+2TTlshwXTx3KVx+REJWJO9XAqoJjeSpQUsmujwlS4bwel5xGYg+aQ9OPawM3WW8QUhl9p3QCzE0BP6fQT/03wGwCU/A4MG0gG/VHD+Bzs6/eAMYdIAfwNlvcA3ILTbRBucdL8J4l5jl1tSS6ZttRmGQuXTAP2SF72Wae6alCOJxX4vTfHh5CFb3M6OF0ybetb32O34YNCqo7M0KpVmMmg0sUHbC0ue8V+5iixXpGJt9RXmyxCzlfcmsy6DRLuN1fAuutQUbz5d8hKYw7mR4+FrAKj1l4Z5g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: authentik-oidc-secrets
      namespace: argocd
    type: Opaque
