---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: paperless
spec:
  encryptedData:
    postgres: AgCwWOjwCad5PFac8P2MnuFyPwKiusfTf/2iwd/kZNsyLzaAKjL+4ExKPWXOLiC8mZ0pWjmJ2f2NbiIOyE+Lvxyah4YHHvJQF3BMln6WiKoJ5bKdhmLd0Vpg1He2D48YfS7NN/WlKnlSuxELi2l3dwFIpOmcYwYvKzpZFirn4lNrLZEvSCyhZ97Bfo4ug/vUzOJfcVbql0O3PQxoP88VHFKgIpScC6oY/C1Atn5gkFzefLLyao/MgU6ivt70CakoaPPpY1ks8Ghp3E/7vmNgm5YJYYlhJDpcGR/yy2m88l3UMYk/DuTxsKFtZWjDunKNu+sdycrowLjorZHwnPn+jUA8oKX7MaYt6rKjYe5YZ7DQVU6W/S68kDWH70Vrc9WglIDdYFBWEipsKa9YpFJ5ahnNqve27h+GB1jUQSUWMhH4kADigu1fol1j7OcNJiuy/QfZHvDnFHcp399itOZmmq46rRaSneWLn+nF3KeKwKIfPJDAXyjMfy1420wZN9yRDSqDAWP4nTWBGplsQwlQwTXxE9+/l+hGkL+fAWZ94JrXhpBxCvYs4vc08Jz9hAGP+SZjPYF76/hODhTM2s4quWBsaTTUzUC9diwXaUgyF3pZPLXy20Gf7opzI7jzDIlPHBeH7XSh7kd4ZKRwIGf2VfDK3p0l1WmmTLXA82paVk+/+wLDq7g+HnAFA3/7rwv+NpyMdDHr/LiJIsLM19V/wdBP
    redis: AgB6HvIgzXpuxyEFnkiXcq2Ao1iJrEdgOmAKYy6XG4/I0mZ2Z0PoSqZnuetRDCK3cpr53pD117EEfU0jJqo7yEiunXSZhRJvqBbdFNV4d7Sv9rVL7mQ4mgpEfFTA3vqjtXQT5a5U6+0/B20lC3psp+JwqU/KxkCqN7xsZuDXDU786HgNIs/cHPEweg/iRkmoNeAEMyiIX9Ygbwo5FoNxcCm/Xl+9MsGcr0f/PLXBGsnfv3J8LzJWkiaLx4YdbNw35PU1vBny98aujWjHeLUIuBUhX/lj79WZDh06D5V2xSsSif/TXaek93I9lpNYAKrGfc2Ml7VN8StnvisQ1W+ReCEYq/bUQbVKJQuiosj5VkJ0DMrTHz/5ea6k5oqj9tXh+IDiNHQF+AsTFiQXRhiKKjqSruAt9lsBALsYltt5MLwZTQUyeg8tmvD0FL+qn4cOqrocGFzIbXzYvIkbjRpnPMU5PRwK5RHgsXqFxDhdNUICULBKpc15zSFUFxfq3y61WHzVlA+dK/yfervx0U4JDJLyhj5KAdhRcMO6MdQHZvnLwVrXE95sT1unq0J6KnagqLPN/6+uBtooNtTW0i2OO7/5XALFfW0HVHxAkpjn5OGBBEIOH/a5/nU1aojdl3HtNcQ2+oY3bVZ7QF6B9pWhh2rXAZo6ziW0hzPUneedEjiBGYtiucwnSZ4L/0Ag+UgtFQUkzWT6mbbRvC2JOEwc5LIv
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: paperless
    type: Opaque
