apiVersion: v1
kind: PersistentVolume
metadata:
  name: qnap-paperless-pv
spec:
  storageClassName: ""
  mountOptions:
    - nfsvers=4
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.185
    path: /paperless
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: qnap-paperless-pv
