helmCharts:
  - name: pocket-id
    repo: https://anza-labs.github.io/charts
    releaseName: pocket-id
    namespace: pocket-id
    version: 2.2.2
    valuesFile: values.yaml

resources:
  - pocket-id-secrets.sealed.yaml
  - integrations/argocd/pocket-id-secrets.sealed.yaml

components:
  - ../../components/tls-ingress

configMapGenerator:
  - name: tls-config
    literals:
      - host=id.nora
      - service=pocket-id
      - port=http
      - pathType=ImplementationSpecific
