---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-secrets
  namespace: pocket-id
spec:
  encryptedData:
    ENCRYPTION_KEY: AgBtz0SxwEcPhQZsOa4RzFdvwbElCM+L0roRop9R1Y1o7jWRAIlUqO9y6E4d8RaAdySlwZfNCbRP4CH+KYFGEAOSM6Ht0vfVVBYACNbZsEntlCRNXPLUkIDCBTcaR7L+4Lenh7ZdNUYrK9ntMy1SL8ywEOlqOSMr8cC5WZZUWVLXAGmDmmcTmtL1sI0BsjG9tVTu96cC9tVGF36USxAoTxWnex+p1OipIFMWYTjPUz6uiqfNmTMpmEU2YD+Si2roX1xlR/qwmlnjDyPnU/rlXvVl6aUHOZS8VNAJUEQYWjlhBBph3eptAdd1tAOe31gLuwF5h69BBUQtNbALhUzCqjbvHs3D00nfGfAds6oFJUE7oXzmq154Pk3wlvhR4IVReVHTT1sDJ6MpU+KQMtkRVPHinfl3G2bSPn6MUDO6GLoGlPD4DaBS5mWLeK65S/FNqm+oNSUoAYbslG5eXbv255XtciVdSRWl2F4DnPxdLto9NI5/9vdRxIeDDC5VUSTKYVfwnQSaxkRedGUgqxc90J3fqwecIvaKBmCS4qQzt0xmQocwYtS9T26TlKvUI9WAiArxuliIOUmzeJlY7NrYfxRvSfg0PbZTBHGgXQPsxYndlAFTpDB/fW88wBmRQrhFSK9IiZIxUgjL2rvQ64ZJbtZbQKybguXceS6MwUzAFxzcOay4xkmzswY+hW42S4tppYRFzZmKur9yukM7Nqg/Lb6Vp8fjzVKhx0hLqwPCmXVNRc2lbjrrsi2kxPIFfQ==
  template:
    metadata:
      name: pocket-id-secrets
      namespace: pocket-id
    type: Opaque
