generate:
    rm rootCA.key
    rm rootCA.crt
    openssl genrsa -out rootCA.key 4096
    openssl req -x509 -new -nodes -key rootCA.key \
        -sha256 -days 3650 \
        -subj "/C=PL/L=Unspecified/CN=Myzopotamia Internal Homelab/O=Myzopotamia/emailAddress=myzek92@gmail.com" \
        -out rootCA.crt