apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
spec:
  secretName: tls
  issuerRef:
    name: nora-ca
    kind: ClusterIssuer
  commonName: HOST_PLACEHOLDER
  dnsNames:
    - HOST_PLACEHOLDER