---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: blog
spec:
  encryptedData:
    .dockerconfigjson: AgBKFOyKo6FaUbNC2+NMVp3PhvwwZKXYGMcpIqaYxLIh013G5tBjHhYc8LXCy774sBPnun/Kl2bUV9xjpsDj56h9y9xQHH46u+PPtWT6BVYmxxzmmd0rm9UFE7ltmtvhIdltVvQu2v4zDSq7xJn8n0a1li5WUME+mtOIFwhtsbmT2aBKDTR5zrXtXE3f3qysCX5bGw4ae/KzPcnvhE6cx+OeQ6WZUhibefoaNrskcQX2ruVFCCc0OqhOSGop0r22XYGcSTfjUT0RTbmUl2uyYy8xKpgH5trA03ie1W3OiS8WLA+KUb71bR5Qlg4WQpzP/Y8vNAr0a8ZQgfSUJ5F32+0OFHN6PBPxbUEaL97tfziGnBQolZcPgs0seLoyBlbhaAYzOpJkagRIBFK3C69gxeNSRDCXuLLV8kwDYAW8CI4PBLNRsQIXaeaXn8/WjrTVxcGBiFwl0bD/rL67A/+KrzhC+OPtkHp4Zhjy5WLP4bmvhKnghSO6YLLKEmeBuGAPUGdzKYZWV4uH4C4h9YDCaGwTo8j/uUGhM3wNalLmkKmMNp5ZoohSaNZE5r2Ys55dQitpRZubnjGDl3F4gYFOZJaGmQxt3rcHvSIlJOJ6OEntmui2iNSPseJt4wlOGsO0ZMDsubKlHnklPdTdOWFfZ6zLsP0PtInZ4EhQRZiEb8V+NaMsqsa7IIt7Q1DgMh0LrD1tUuOQta+y8MgsYbFVvvzj957ZwQmoLmerg3xBndaelrv3AAOhffqNCX3KryrEu1KbF4sLNRUdjt/dPib2eI17cKvmpygbFQnfZIegTHLNa95KDNNC2kVr1A/lgAguc6OSwFa+lq29AISVRiq+eev7Xp7+YAV+BsPcHBFszifnHGgte9cu2nYy4qd0iF8vm69ODw1PSjP71cnQsxEAnYtJPqxhJ4FRqpySBB1QC52bGA==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: blog
    type: kubernetes.io/dockerconfigjson
