---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: valheim-secret
  namespace: valheim
spec:
  encryptedData:
    playit-secret: AgB5Kmq7fO6oux6js+z9BUYu603RLgmDJAg7MmWih6DrFtTxQsf2SzZaqaYbrI2wyY8b1etK1z0JZQC77cRlEa/fCPtgwibdMNUVcfoW7/nFEOyvHOMp8Cn2tGGEERADrREEEghZRj+MzVeZCcXKkddqn4+WIWXkHjFS9JYfWN7tXoe+HQcyXVHJQFrqLeIgtYgn5KYPbX3N32GChOVrFkmhgDBu9sFrEq5aE1y8LCPmt+aa7usBhkF7xfrxSZJ9uqtecpL40BOLmD64ZG88l3ELhHSBjwwWa3eSbFeGHCcLiQ/Z5piVD8Wktm+YbPc4BE6+ZfdF595DBPKbjmzPS83VHrTwJmxQkkjP2C1qqAe2Ie7TM57+rV7JwTiGOKfRaK3xL2BiUkRuh73I6ML1BUk/e2+QlDoIg0M8TzmrfV+uZ9V9X/RThbOjaZ3aKarUAD0zFzewUkB2mS3aoK8fbKYYJuuL33bgITEJgywu8mEOnUwZ5Ikjh5EjfKXLa11hOxCgihWsrysTSYv1s/aIBXy4+Ifd1eta3NI16vOJMg2m+rRn4yN6hzKL5h88vAPwRV4+0j/04UC2eLu+fxQUMcvvULh5KUvy/tfkMY0QPwxW/1A+QMhvUFk5dEcfH4rix/WIRRw7R2TXAf+tZzTJnPARPpJTOtg4Jzyc7/QgDDciwhfcfp3czsC0mFbZ0SyQLt1htt39KqHuEdL3th+q9ce8ssexXtcmCayBMdWgvOOy9+do/fXmaJwhdKHf7LLYOM2Hu7Vc5FNaTz9kLtdYJ71R
    server-password: AgBk9VTUPvZ6iVOMx/HG0j2GGwdmkkgR3Bz14Y+c/cOUq1dCoQjDnJKOdfKuluGWApRR3qGSQa+zm36CorOVkPBrne2jqc6LcpXQdo2n4BrOi/ixg9gTI9gBD0zisgRCldE0sSK7elETVT9UUsx4unN1Dbv+MK3+p7nHgWgie0ttjVXWL9rzOmVlouI0b0ZOUzye957NmyQ3hJc+2LLvQjXd+WT9Cy/hycNY0ise+Prb7Co0O3RcZIcZZU/RCFix7o3YV3tvywhmYXTXQfGzjn3tug/aZ3MlgSL/RI4xzPAtWwdn9iqgAhivxVOcftPDQug5Q3boQjNsDoYbYo0LJWwoCtNRg9rvATApuFNKxXmlnKeHkqNJ5uG5/SgHNh0gps282pDIArYZN+qTew+5UUUq3zOXmEo6QPPpvdaeTzrOt34CauOFqhgwTyr5ngiU9IMDJ5KODVIGkJLSyWsruZ70OgXSDd7VhkjuB6n9BSzFCT8aVpjBpzj3EVN//1yB0KlGZwOFTLovXSEe2ASh/yPDca2y59i+wC+r2jnryTk8I8krjLnUE9eJQUTtML8+sorpgU6af2nGEhlaRPrY1msxBwRWIYJVxsJI054PiOGTapQEPW7EDbR0rfEj2EsG3br6Ks8zPdYGF8p6zxr5NB+46e96B/WohPgjDvbSfIV0MIE6D8XR6QPMNGx3K7heWJCPC1BobEn9UkZhNVV+JI8pNA==
  template:
    metadata:
      creationTimestamp: null
      name: valheim-secret
      namespace: valheim
    type: Opaque
