---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valheim-secret
  namespace: valheim
spec:
  encryptedData:
    server-password: AgCkpBFO1cCtOhcI525cc7K9yZkuE/ekb5TCtQgbtqfXUa+z27TjRebHOllUDXQaWVGM6LLaPXWGP2RyyLyUgD/g8pK5TPfZv20ZrfFDqSGagEBKiNsnXzJsdfO7/QdXqdhijkQw59/BsWgwAqZDyCFbk5F/WIObsukUxnwqAxTUPB2hxijsrV3AJK6rB9i3FbDBLR13SjPCSg/KpsDMvk/dIXeCpGW4O+084vGKRGVc8YgftlncIILpM/n/h2Pt85QuoGjjQluIfHrK9rL0RuWUaFJdcbQAbqFovmNdUzrX0R4kKIsE1uTznwFFJIodkRKdiAgUGFv6c8J4RMDaetpZrdAPfZE/huhaCdGNV6HtUFlfcScfW2VmLYs6XqgZT+T1fCJkm3L+slhaQI5a7pJhvtIN3RutUv4/cnTvxyF9oOFWRoTzvvIIr8g4Ns3/0Gs2lhlRouj5/sNPoV9kIaHeVl8oreBGnR3xrMSSMWSKuZZNxqVQCOd7UiuOilfd2vmPy76v8i8Bzdpggsp7A8ubSCVgFxxiJKKBm7zuqkF3XDU0h17RC/2kJ9f+/lryJIViO68cD6UslW+Iwv/njMl4ETV+1VFswFyFatq2XQMWd5KjuL09lLRAlLdHmRyoRLAdTdbXufExs5cD5Ri22aglEviSuKIPtnI5sXjtF34rqOT4Dm976oKhz2FtJWfE9Xs4qEoUprc/CrVV4ARf4E3WBw==
  template:
    metadata:
      name: valheim-secret
      namespace: valheim
    type: Opaque
