apiVersion: batch/v1
kind: Job
metadata:
  name: immich-backup-media
  namespace: immich
  labels:
    app: immich-backup
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: immich-backup
    spec:
      restartPolicy: Never
      containers:
        - name: backup
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Install rsync"
              apk add --no-cache rsync openssh-client

              echo "Ensuring target directory exists..."
              ssh -i /offsite-ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
                pi@192.168.178.69 "mkdir -p /mnt/backup/immich/data"
              
              echo "Starting media backup..."
              rsync -avh --delete \
                -e "ssh -i /offsite-ssh/id_ed25519 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
                /data/ \
                pi@192.168.178.69:/mnt/backup/immich/data/

              echo "Backup completed."
          volumeMounts:
            - name: immich-data
              mountPath: /data
            - name: offsite-ssh-key
              mountPath: /offsite-ssh
      volumes:
        - name: immich-data
          persistentVolumeClaim:
            claimName: immich-data-nas
        - name: offsite-ssh-key
          secret:
            secretName: offsite-ssh-key
            defaultMode: 0600
