---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-admin
  namespace: forgejo
spec:
  encryptedData:
    password: AgBlezN4/sbZKUMKlE8Y3JATFQTPPhGas/edZ30YYCy4mb1EWZwvdW0YzdxQqYOwHVFsmiSquv2blP6ifKDrJ6VC2wq1uX6sxVZbQ2d8f+zES5z3l3XL6Vy9HAqotmPCDh169fzJRVgbVNruBl8IjLK7ChrTjCUsIV6uVqEUhPMCvcBkdRvBnHGb7zoHfTJ97y3GQlqmaO7oFf9GmIf9B5BblI1r3K0b9xIP0KBu48eCfg+3QWkcVu+BWEFixWJovABDsU8pzBnYX5+0KcNe9jPv1m17BV0V4J3hSXNsy6YIAghd1jOYocCw6P4/wHj1r2MZYSS7agUYX7d4TcfsVAwNad+fR6azIaIGw0eFLlI6Gd29IjrqPJK9tNqhAioHq91kQCWPMeIzP42zgC36U/ZrfhlLtlNtTt34PcciVF5nmCNZKZnlspM6rp/db5zokCQ1wW0JgR6wnEgUezeesTYmXIH9OfOVgtc7oepKx1LOvunGbKyCXdgpM+BlEz7o/L9v26U6+TAbB4lR2Qw9FuvZFHxu6Ht1WyRL4g3S8aeRrhi9X6kwRvWbK69l7hmpdfINteQD3rbk5XbPc4Nfx7MRUtnFtz6PthThuYn2s9AwXll/C95Tl8NHJxVoFOqhLCmUt2WNUZyYbqmNe5gzD1VYkS3boXfuTcZJssNFIETHkRKc45FQxoegcYM0/s1lV+z0Ovdf1zLCz8a3NsSHogrD
    username: AgASxn7szNIwPYeR62IvX3FzICbm5ArnC4zVmwaa7YcG4uCwTdh0nFnTTYkJBhcnb4a6AGzMvQln8LNf4xLuh4sjLKqI/fDTY2RJl4zmPBAE+cDlxVXSViCCbCBdU8oOZAsXbw1E/sz37VMb9b5DjLZ90pJCV8PFGtT0ZWqiyoSzSefYhamKunhKrZYqKW3Femtti4T9IG1bz/Kf7qJ2oBO1/uy2r0tsqDeAnpndVJ2JGIu3KaJ6pkvpabOANo+3N1tdQw1E3VWrBm+CpjF/7i5JRMQ8fYpfur9kxNdj8lgWUs1Rjve93EjXeOueWa4qqLZK1Aknu+VhgbKz/LHDJsAwAeGyOz69CqK1CqhCGnNkccx+s3roH+GCIRXuBXk0gBhmfRyp6tBVwAa08wYyQklYSs8ItvNwMr7+s6vwHaYLloDCKAxiZbhZhOArkrHmXLTmBj8Bi8VCiM7vVM4l/J8TMHprJw/LimjqgBlQu+9+NRdbQskLMHZ4IMRahOslEiYYhSrUgN4TLP0cfCuu/x4y2codJ0+/4QfjjQ3KQaSx848qpEsuICfqaHqcVSMJWinYYiCd113JV10OZxN4Jtt08RIUYs2sr7u5IczAORkeq3wgZqaBbZ6ku8Ubn+zx6QUs/MI9/E9w6zyeGHq+RErHSDe2sk8qunbeLdadyx4W7Ytam7ZMzzvNAKr2gBbZNcl3oxec5A==
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-admin
      namespace: forgejo
    type: Opaque
