apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo

helmCharts:
  - name: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    version: 17.1.5
    releaseName: forgejo
    namespace: forgejo
    valuesFile: values.yaml

components:
  - ../../components/tls-ingress

resources:
  - admin-secret.sealed.yaml

configMapGenerator:
  - name: tls-config
    literals:
      - host=forgejo.nora
      - service=forgejo-http
      - port=http
      - pathType=Prefix