---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: acolyte
spec:
  encryptedData:
    .dockerconfigjson: AgBoc9/GOjORy8zP+SVv8EaM5kzVJlPgW6nQ5GVxrOjDeTC2jLRlXyTKD/DS5wDUYrKdpC6iA3iPhXtKggRGT9leWfUsK/Uxs7EMO/VgCpPsvpjcL2sdZCdKOyDB5vzcQPiB576movMkm6ng3CfykvncQts+JMJdPXes4yJOPv3QZQWz4e0wZFbQVU47n+NXMJOTWsRRk/HgkS5C89ryvvhx07X5DNGCtg83RhjknCuHyRvsk5+x90f662VU2fdCd/XpHoLJeiB3zqqSpcDuxw7ssczZtDSA3s+1+k1I3t6SrWm/NRhz6MZnQ7Qw5oBzGRC/pV4YuWN+SMK26s32z2iM7Todelv09MnGhZ8ZN1Q48EymnBK7AJeWJiIfFGbM4cVRUsbqwVFI0zyYrQZlSyrwIPr/D9b1nANHcBH5mBmyN3RzzyyshV5I945TOEIJtA4Q9oOCy6Zi5bfXpux510wuWs0y3Lixo2sHvDCOMJiBd9RhYd99WSk5XBJGHjaSh/42sdDJP55VU8jnhvfe/c7u1HX5uxP/wNvXOccagOdJfXnWrDLnzRhPufQ1EveloZzQwkfIxfxgQDKEt/O8LlnLfku09XjFLCMfR7hJboJJcxmSVsazNlBRqAQPXvQ3Ui2hZSFKLIcGXcZJ6qrpEORTBGLrM0CIS7xaMkYoCqEn0bM9QLDE5m9axzIbqDIjPEncKPHcSDGUv69RBWdp3ppWxh52KkMXl35jE0kWJ8iDSJSqUqefkIV2avsi+6t8wX65NixH3id0FSlUCgr+J+t9I+Qn7VDGDjPFdlG19UUwkC3q9TcM658HT33sBJGNtCSoWZdHndk9tXcH3amM99pf0+1OfWqT/CgQXrDw/mVtshY38H34N826ayB7M/AxqrIJCup1sGRsvMfSI6Xe4H90IB+XckN2O4TgiO01nlmlRw==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: acolyte
    type: kubernetes.io/dockerconfigjson
