apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-backup-orchestrator
  namespace: paperless
spec:
  schedule: "0 3 * * *"
  
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: paperless-backup-sa
          
          containers:
            - name: orchestrator
              image: bitnami/kubectl:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  echo "Scaling Paperless down..."
                  kubectl scale deploy paperless --replicas=0

                  echo "Running media backup..."
                  kubectl delete job paperless-backup-media --ignore-not-found
                  kubectl apply -f /configs/backup-media-job.yaml
                  kubectl wait job/paperless-backup-media --for=condition=complete --timeout=2m

                  echo "Running DB backup..."
                  kubectl delete job paperless-backup-db --ignore-not-found
                  kubectl apply -f /configs/backup-db-job.yaml
                  kubectl wait job/paperless-backup-db --for=condition=complete --timeout=2m

                  echo "Running redis backup..."
                  kubectl delete job paperless-backup-redis --ignore-not-found
                  kubectl apply -f /configs/backup-redis-job.yaml
                  kubectl wait job/paperless-backup-redis --for=condition=complete --timeout=2m

                  echo "Scaling Paperless back up..."
                  kubectl scale deploy paperless --replicas=1

                  curl \
                    -H "Authorization: Bearer $NTFY_TOKEN" \
                    -H "Priority: min" -H "Tags: white_check_mark" \
                    -d "Paperless backup successful" \
                    --insecure \
                    https://ntfy.nora/backups

                  echo "Backup complete."
              envFrom: []
              volumeMounts:
                - name: job-definitions
                  mountPath: /configs
          
          volumes:
            - name: job-definitions
              configMap:
                name: paperless-backup-job-definitions
