apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance
spec:
  rules:
    - host: glance.nora
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glance
                port:
                  number: 8080