namespace: glance

generatorOptions:
  disableNameSuffixHash: true

components:
  - ../../components/tls-ingress

helmCharts:
  - name: glance
    repo: oci://ghcr.io/lukasdietrich/glance-k8s/chart
    version: v0.8.5
    releaseName: glance
    namespace: glance
    valuesFile: values.yaml

configMapGenerator:
  - name: tls-config
    literals:
      - host=glance.nora
      - service=glance
      - port=http
      - pathType=Prefix