glance:
  server:
    port: 8080

  pages:
    - name: Home
      columns:
        - size: full
          widgets:
            - type: clock
              hour-format: 24h

            - type: weather
              location: Dębica, Poland

            - type: bookmarks
              groups:
                - title: Homelab
                  links:
                    - title: Homepage
                      url: https://home.nora

                    - title: Jellyfin
                      url: https://jellyfin.media.nora

                    - title: Immich
                      url: https://immich.nora