glance:
  server:
    port: 8080

  pages:
    - name: Home
      columns:
        - size: full
          widgets:
            - type: clock
              hour-format: 24h

            - type: weather
              location: Dębica, Poland

    - name: Homepage
      columns:
        - size: full
          widgets:
            - type: iframe
              source: https://homepage.nora
              height: 1200