configs:
  params:
    server.insecure: true
  secret:
    argocdServerAdminPassword: $2y$10$4x03OZcmTpuEcI.sk53U8.UYyTVaCJXMUgNTg81eKG.YgUwgV1tRG
  cm:
    kustomize.buildOptions: --enable-helm
    url: http://argocd.ether
    oidc.config: |
      name: Authentik
      issuer: http://authentik.ether/application/o/argocd/
      clientID: aFSFW4aaKGi9oizCImusjLuTBxe2xJ2SNEm9QsiO
      clientSecret: $authentik-secrets:client-secret
      requestedScopes: ["openid", "profile", "email", "groups"]
