---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: renovate-env
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_GITHUB_COM_TOKEN: AgAeyL87etxRrkLrD5tvIIyQLM1dFcE0da3W0HRQ/UJOHlRmdtoxpUyqaLiy3rYFFV6exU7yhfqO0BGdDBpZ5YDPJaPrSCVRkBurhosJOHKqg01svK2deWtStNnCuNrmeUKNLyFUs+emVlJ04ZtgiDJkkhwaxyW7aDrdIrf5Zhg17QF1EHj8/k0F/JfkcnhCkR0bKib1gH1VAcunjbHO8o2l22hfDKuWbMrohtSNv9yYiGEgE+BB8V/hWzatxrfA226ap6gp0fvtgg1RuBwM4HdJdKJf2+D5C2xv9iwdYvvVrnzpxhiwyza3Xx/P+BbfGIBz1eCtsLMUwHs9qD7roHjBH3zlO7nnh8Iagtfd1RxpnVcGJGc5zPHZ1ZVxWI5jB4GXGwiXZIWQnkjhhDEJmAfAUXXQ9Mt3/FRrjhvbRpTDhtLfA89S5XF1tXNUR4JB7y7MIPfzvUeMBjn05ehW3Y4UNBQGop1RpjbssEHlXpJAxZe2K/miW9P5w/fv88ZMjS1kno7UKf0D3VrciLdgNozZ6drLn9jnZ1nCxc3GKB7dOpQmXEbK35qQk1dl36dUdjUlteI2vX9gviL0qop4jn6Apeu8VxXPT3Rrqfd703YQ69e2zos0dv4rdXxdGbFH03JuBKD9xVMNhfxLri0/XmjZOG1YGW/LITHnrRN6fMEM0jQv1js94ClAM6ZMRMFOd2vij8RPsXMfUo9q1O8zvuLXxRf1whshKqClas4KRl7gH/OvkGHPJ6vuMtcM7X7VZgQIzRf6DDYD9cFPLuH97mtHgtuBlRW+1LpxCK1G5RWx5M8MjnI9GkTq/gEGZJE=
    RENOVATE_TOKEN: AgCqN4mtte6B9yhGIeFLKNUdhZJR9OoXliaGDl15lZRxW63Wq3+FOPC/B1sxIEsUNk9P8LpdJ+vwOVqMW7Mn/tz6tp2rGliMN6KJtn8PmSlaDLdlNZvN0RfFM5/X5eG/JG4rjrusRihA2cYgD93Xb1Pl1oEKhrVAxB7rOFAn5IuQtQHbZUgAOi6FyHSrtb3tMsKewXktn+6qsZ1fcjbMRHdhImNHeaFd+hn3KnLCnRe0k2KJvsJnqn8kIVMMfxXZ7bpWIzU53FvzkOWF7VHf4yb74JBu5cM7MKl9+8vDSIsv4zCT63Cc0dcvIw0h8QKcqI53Z0UwSbV63q4L3Y9Dlqm1GMqBDgxDXFvIEHAa46e6XTUGDcjleRVOKf+TLZdDzMQshLfcPhmyzcNGxAVQrGzl13tCR98bXerJ2OaxpL9Xx49SjgBUU7QUviWUmkbqWFjoAf4pM0ldjQyjYnsw3d3vLnOzh1aXi2yvzYe4UEaZhLuuz1KWSUZiuMgDypinGTXX0pTc+FBjWqiOhGYvhxuMTmd4hDjcq7J7+zaspm7VhEllM0IDgnnhJdDDQfXg3Z3DQHqF5rUNw3abaW5rmSVHOMI2tUDG36fMzsBACjwD4uk+Or/GiwNQLthidFfDMWV3TLZRsvpMYrgXe2zr9lGCiz18RoBNmAWD2JD73x3MHPIOGxllfs73wIOFls7F2oXO3JOC2G7EQiF0k+XLmmMO9bHpT2rEGyuG8eZO/Kpnn/HbozSskplGs3Cw7gcKXvCrnM5l9AjVNismJ5IkjuaSwbOnGXx70P10IKr/L3TI/5e468dDc8LyXWnB8Qc=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-env
      namespace: renovate
    type: Opaque
