helmCharts:
  - name: sonarr
    repo: https://charts.pree.dev
    version: 1.17.0
    releaseName: sonarr
    namespace: media
    valuesFile: values.yaml

resources:
  - config-pvc.yaml

generatorOptions:
  disableNameSuffixHash: true

components:
  - ../../../components/tls-ingress

configMapGenerator:
  - name: tls-config-sonarr
    literals:
      - host=sonarr.nora
      - service=sonarr
      - port=http
      - pathType=Prefix