namespace: seafile

helmCharts:
  - name: seafile
    repo: https://haiwen.github.io/seafile-helm-chart/repo
    releaseName: seafile/ce
    namespace: seafile
    version: "13.0"
    #valuesFile: values.yaml