namespace: seafile

components:
  - ../../components/tls-ingress

helmCharts:
  - name: redis
    repo: oci://registry-1.docker.io/cloudpirates
    releaseName: redis
    namespace: seafile
    version: "0.26.8"
    valuesFile: redis-values.yaml
  - name: ce
    repo: https://haiwen.github.io/seafile-helm-chart/repo
    releaseName: seafile
    namespace: seafile
    version: "13.0"
    valuesFile: values.yaml

resources:
  - mysql/db-credentials-secret.sealed.yaml
  - mysql/statefulset.yaml
  - mysql/service.yaml
  - seafile-secret.sealed.yaml

configMapGenerator:
  - name: tls-config
    literals:
      - host=seafile.nora
      - service=seafile
      - port=80
      - pathType=Prefix