seafile:
  initMode: true

  # The following are the configurations of seafile container
  configs:
    image: seafileltd/seafile-mc:13.0-latest 
    seafileDataVolume: 
      storage: 10Gi
  
  # The following are environments of seafile services
  env:
    # for Seafile server
    TIME_ZONE: "UTC"
    SEAFILE_LOG_TO_STDOUT: "true"
    SITE_ROOT: "/"
    SEAFILE_SERVER_HOSTNAME: "<required>"
    SEAFILE_SERVER_PROTOCOL: "https"

    # for database
    SEAFILE_MYSQL_DB_HOST: "<required>"
    SEAFILE_MYSQL_DB_PORT: "3306"
    SEAFILE_MYSQL_DB_USER: "seafile"
    SEAFILE_MYSQL_DB_CCNET_DB_NAME: "ccnet_db"
    SEAFILE_MYSQL_DB_SEAFILE_DB_NAME: "seafile_db"
    SEAFILE_MYSQL_DB_SEAHUB_DB_NAME: "seahub_db"

    # for cache
    CACHE_PROVIDER: "redis"

    ## for redis
    REDIS_HOST: ""
    REDIS_PORT: "6379"

    ## for memcached
    MEMCACHED_HOST: ""
    MEMCACHED_PORT: "11211"

    # for notification
    ENABLE_NOTIFICATION_SERVER: "false"
    NOTIFICATION_SERVER_URL: ""

    # for seadoc
    ENABLE_SEADOC: "false"
    SEADOC_SERVER_URL: "" # only valid in ENABLE_SEADOC = true

    # for Seafile AI
    ENABLE_SEAFILE_AI: "false"
    ENABLE_FACE_RECOGNITION: "false"
    SEAFILE_AI_SERVER_URL: ""

    # for Metadata server
    MD_FILE_COUNT_LIMIT: "100000"

    # initialization (only valid in first-time deployment and initMode = true)

    ## for Seafile admin
    INIT_SEAFILE_ADMIN_EMAIL: "<required>"

  # if you are using another secret name / key for seafile or mysql, please make correct the following fields:
  #secretsMap:
  #  DB_ROOT_PASSWD:  # Env's name
  #    secret: seafile-secret # secret's name, `seafile-secret` if not specify
  #    key: INIT_SEAFILE_MYSQL_ROOT_PASSWORD # secret's key, `Env's name` if not specify
  
  # extra configurations
  extraResources: {}
  extraEnv: []
  extraVolumes: []