helmCharts:
  - name: victoria-logs-single
    repo: https://victoriametrics.github.io/helm-charts/
    releaseName: vls
    namespace: monitoring
    version: 0.13.9
    valuesFile: values.yaml
  - name: victoria-logs-collector
    repo: https://victoriametrics.github.io/helm-charts/
    releaseName: vlogs-collector
    namespace: monitoring
    valuesFile: collector-values.yaml