apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-cache-pvc
  namespace: github-actions-runners-ether
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn