---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-postgres-credentials
  namespace: immich
spec:
  encryptedData:
    password: AgB534Faa5wDNHpDYahnJNnVHaT2lSSjiEQhWo00yAhcqXHqOfqfyV1Mi51qjTv4q5BvCmRW+rqbdvt5HPveKgeFGn0FKgzjSuabFb0ZM3/lJEFhUSENdqoM+pRQEYkFDz7eftkOsUSZsMbG61ufe71C1fnvHLVAEDVMCsh/eOA2HUoCirZCoNYH1citM54eYsPk6drsair6q1RFBufKYslcpdzgEB7SgHgv00lqcS2KaLuh+lg+D74YkR6d0Rh43Rgx6gVw2458nA4xZjYg1yvJH09hFamwT9fVZ8LFCkPvTwmcNj6wZfBZJo8pOeRBKWOUns8bcq3+GUadyfdomBTGjsnxipOHrRFOmtCHHth0LPk/eh+JxO1M0DkC60+LfOiNzl5zqlmG1c7O6x4UQLaknFzpu4nxavnmnoLqlgP0PkZDa2NBSoPsM5k37UXKKyv2XsJ0kgBP3IOB3MzFk0DsyYPpPiqaUBRtpsCox8kWsEiGHiLitHX7xHTGe0F/0tpU5OLOJvW6pQOxj0cwE1mdeM29M0UpyByf8/XA5vOpFwIkeFvXKcnh/h2513Kfj/QUYdkNnI/Vmdz/qIhn3YLEtO7jpMQIdTS2M7GYJdD4S+hYEMNcRL+rDMlYtn5UwRnNm3kcAthC8XG7jc4z8GRLRO1BAL3SyDsr4/TFtlGeIhnIFj+GQdODgKGw2w50noIAXwLihT3JBboghkYZy1k1
  template:
    metadata:
      creationTimestamp: null
      name: immich-postgres-credentials
      namespace: immich
    type: Opaque
