apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-nora-tls-cert
  namespace: immich
spec:
  secretName: immich-nora-tls
  issuerRef:
    name: nora-ca
    kind: ClusterIssuer
  commonName: photos.nora
  dnsNames:
    - photos.nora