helmCharts:
  - name: prowlarr
    repo: https://charts.pree.dev
    version: 1.54.0
    releaseName: prowlarr
    namespace: media
    valuesFile: values.yaml

resources:
  - config-pvc.yaml

generatorOptions:
  disableNameSuffixHash: true

components:
  - ../../../components/tls-ingress

configMapGenerator:
  - name: tls-config-prowlarr
    literals:
      - host=prowlarr.nora
      - service=prowlarr
      - port=http
      - pathType=Prefix