namespace: syncthing

components:
  - ../../components/tls-ingress

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - pv-patch.yaml

configMapGenerator:
  - name: tls-config
    literals:
      - host=sync.nora
      - service=syncthing
      - port=web
      - pathType=Prefix
  