apiVersion: v1
kind: Service
metadata:
  name: syncthing
  # annotations:
  #   components.nora/nginx-proxy: enabled
spec:
  type: ClusterIP
  selector:
    app: syncthing
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort:  web
    # - name: http-ntfy-nginx
    #   protocol: TCP
    #   port: 8080
    #   targetPort:  http-nginx