apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/rskupnik/ether.git
    targetRevision: argo-migration
    path: argo/apps/authelia
  destination:
    server: https://kubernetes.default.svc
    namespace: authelia
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true
