apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: infra
  source:
    repoURL: https://github.com/rskupnik/ether.git
    targetRevision: argo-migration
    path: argo/apps/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  ignoreDifferences:
    - group: metallb.io
      kind: BGPPeer
      jsonPointers:
        - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
