apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: https://github.com/rskupnik/ether.git
    targetRevision: HEAD
    path: argo/apps/ntfy
  destination:
    server: https://kubernetes.default.svc
    namespace: ntfy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true
