apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pocket-id
  namespace: argocd
spec:
  project: applications
  source:
    repoURL: https://github.com/rskupnik/ether.git
    targetRevision: argo-migration
    path: argo/apps/pocket-id
  destination:
    server: https://kubernetes.default.svc
    namespace: pocket-id
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true
