namespace: upsnap

components:
  - ../../components/tls-ingress

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: tls-config
    literals:
      - host=upsnap.nora
      - service=upsnap
      - port=web
      - pathType=Prefix