fullnameOverride: bazarr

env:
  - name: TZ
    value: Europe/Warsaw

persistence:
  enabled: true
  size: 2Gi
  storageClass: longhorn

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
