fullnameOverride: bazarr

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"
  - name: TZ
    value: Europe/Warsaw

persistence:
  enabled: true
  size: 2Gi
  storageClass: longhorn

volumes:
  - name: config
    persistentVolumeClaim:
      claimName: bazarr-config-iscsi-pvc
  - name: movies
    persistentVolumeClaim:
      claimName: media-center-data
  - name: tv
    persistentVolumeClaim:
      claimName: media-center-data

nodeSelector:
  kubernetes.io/hostname: ethernode1

volumeMounts:
  - name: config
    mountPath: /config
  - name: movies
    mountPath: /movies
  - name: tv
    mountPath: /tv

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
