apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-nora-tls-cert
  namespace: longhorn-system
spec:
  secretName: longhorn-nora-tls
  issuerRef:
    name: nora-ca
    kind: ClusterIssuer
  commonName: longhorn.nora
  dnsNames:
    - longhorn.nora