helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    releaseName: jellyfin
    namespace: jellyfin
    version: 3.2.0
    valuesFile: values.yaml

generatorOptions:
  disableNameSuffixHash: true

components:
  - ../../components/tls-ingress

resources:
  - storage.yaml

configMapGenerator:
  - name: tls-config
    literals:
      - host=jellyfin.nora
      - service=jellyfin
      - port=http
      - pathType=Prefix
