fullnameOverride: seerr

image:
  registry: ghcr.io
  repository: seerr-team/seerr
  tag: v3.4.1
  pullPolicy: IfNotPresent

extraEnv:
  - name: TZ
    value: Europe/Warsaw

config:
  persistence:
    existingClaim: seerr-config

service:
  type: ClusterIP
  port: 80

podSecurityContext:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: false

  capabilities:
    drop:
      - ALL

  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    memory: 1Gi

ingress:
  enabled: false

route:
  main:
    enabled: false