---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCk4ZPfVDut7UbYuGJH0/u2M02XgBiCx6sa+fuv7aFavYd52ih9U2JxWemFNzWem1lpX5xLVWthIyqNjeCpJxj6Gq/I445nk4Wsf6SdvMzuGc85DeDcJs4DpVYQMHGRkbxelWV3WEnneOS8LQNEZwGlOydkcwwS7XPCOzPLGmvMwYLFRY2MIMydtZgeHHGY25dKgav3wzFGXL66OndfS5EWcbogm1V1QjH4RsN09FsCrUuXBbs+rzegmqGNMTVBd3LdwzY0Ik/r3kHgjnzDPjUY82PmZBpLP1IGz11J5P2XWjtNXu2Y8pt54CfB7o/X5Nr26taMip1FLR4q4act3EQoLG9U/RGsWASzMPKyUvuXEtN2PneFXomjfID0RDIgsYeWRFgtLYvE7JIJohetiDUHWzZFWE78rKElFbjHtEzF3pSBYpCBQqNmOc+ADZVMujxUo9RoSR0RGzZv0jEHUdTOm0rWkMKKyPxbol72UMixM1Sy1pQ7HNy8nCS5tbH4EDbY8F6SOkZthwrldYU7uNSI8u8H/n/EdENg2I4++2obG1/kH65r1KO1ff5MCIFnBuzTXOLJ30IUskFoPLYTrKsMrFI1rR2kl43W7c2RVy2FQAcbvTetnGPRDxkjjTbwbstmMvswuHn4lwGsfGP5oSpYt0HHsYvXKcbp/g1gvLoU/Do/R7xYZh3oVOiv4TibBzJSSDwSu9G3f58c5+Y1oPvwF68ddPxtVioCQ1PFsyeXo9AQXQuQR6mR//D3i0/KHxVwjZdb4g==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
    type: Opaque
