---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAhsybHgd7ZUG4dtpaFkRAjBdYvkBBbjzA3H19rmyHuKFT7+QnYM1XH8ryHdDAhdc51Ca4Vpa5a4GLj5kMKhm9us4dQnTdtx/KlkpZHdG4bwPQFdp04M7yinv0Gfjt2Xq4Yqo/o0X4hyFNFX0gB0h5W1wzC3Y+TRNef1FDupuK54Ow0b9Z6VzqxCRIgvbVYWL6oQlc7O7eq2otrSeEtp5f1AcZyw1c+yX/ZJr4f77NR3Sm7IWep9bPaag9Q4KVwCEc3djs/Juz2VVGGNpHZ9Ep0i0xkB9FCVomIQaYkBfIrn5OakeQ1mKnF6L/MUgdb1ou4mUT11V5A33Q5RhCZ/qR0lLsJ04byqMHuJYgWj99kNskD7o9LDX9jh7ttOAuHoYtgHNwgUPuIuOeOUjlK/6KAuGXonVutPDQyM9tC7ds6UUstFodBNKrQXxiWBBDPnELDEO9CAEBbiBVz9r/D1cEHZLoLN1BrncWS6xPZjCwDkHHDat27p2m98/u07tUwW9Jy7Q9Lb7QPJWRJ1VWeqIuT49hqP4X4kzKAS2AzQAUYIsUYjqhNvRjpZi8tAqlL4rq7AF8m0RisF1OI4uP74dLRiB930wqujhL3anKUj2pHsdPwtbDtbdbWiwO6ZlufQUtVOvAL2OcHbn0/S/QwhRoyA87du2HOxfTz6OC6bFhv1pxj0hqxqV8E6m6RIgkoOjeAJTMklfE4afD4f/ebiURrb+WBcFwSPnsmU0HL8/y+QczVgKsUVZ/UKwf9znG2tqpBjn69mQoZWo0E4G2qLdhwUpzJ3XAko5In18QeDcq6I8Cbp6lSBgvSFnZRggCi/0fzGFybiU2xcKXUhMReTEPfmXQ5xXLjbWHUH8nxD7bf77+/Pwrjo1hgegaPTGW4RlXrf4LYEVDN6zax0NjCkOzKASDieu4T3Q5IREYbW29/
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflare
    type: Opaque
