---
# This is a Sealed Secret by bitnami
# It was sealed locally with this command:
# kubeseal --controller-name sealed-secrets --controller-namespace sealed-secrets -f password-secret.yaml -w password-secret-sealed.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-password
  namespace: pihole
spec:
  encryptedData:
    password: AgAiWVxXoELBd70kke5MFo3CPcMTibCqjQeqyeASq2ObKU49zWUJr/T7eKmDBI/nzLqjYNjJC2ueeu/OTGBH9+vQF090kqwKNNYMIvQDmzgBu1QZRVHynmQfuHr29mV+BqSD0MgZqXYKLbHHtywD4z+FC/NG4H3MHMTBdNzWFU4xlqcEU/08QBzDIh9b+g3Mi9UZ1EiqMkA7BXTjYXlf+PqzZrEXXQOWUjppmvLhsmi9h+tuI6yX2WEZg12sCPXp+XYm1ZYafAuEXcpD1iNBbdsa3ElvmmGOmipzmRuEiIzgpl02t1kG+SVyy7/VPtiSg8XeIrxodM1kRliqPrh6eQPh7VQrJxxpq7QULRLILGLdZ4L0AeDE7hL93jWVpu7MB68s0iQKCeM9rG+YQPPVBmUICq3UF7lHw8nQlx2Vy9XgotRkBzvso9AfhA9e4Uu8dNFi8tgan408dDXFyzi/FxJdPdxYpXV4ptpgSNFj+3wl0YdVZTvzfWU4v3IAKaKpUfsU/5TzMCZ3OsS4UKtefr2bggI5w4gqIIQTiFuq1yXOKBqI2ONFe5alrS0a/ilqQumDhzqLlqf+Tvc+4LjD4r0gMoX1Svf3RqPQGdSuFEXkj1gLe6KHopC/Rmf2zvhoHloPcrDINPiAM42L1yIgtPiHpQe0z1mFA0hi72M5FKfHZIRBhLbK3OGCTL+Re5cEIE5T5UVs9n4KI0GS7A==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-password
      namespace: pihole
    type: Opaque
