apiVersion: v1
kind: Service
metadata:
  name: pihole-tailscale
  namespace: pihole
  annotations:
    tailscale.com/hostname: pihole-dns
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: pihole
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP