---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id-oidc-secrets
  namespace: argocd
spec:
  encryptedData:
    client-secret: AgBENawFVwG+icMKp75mHZ4Q02qUgkPbi26/TZkHzjcXMfEI++/6jNDK6TXm3HsU6HDhLv0FJluzEaMHJQnaYaci5kBpzB1vpixk6+xm0kNcIRZqRH0gNxATFAkUoc0PRgwHhUSeZlNW20/RsfI6AltKJPLo0PgxoUvPNrgyMpr6dmSx/XQ+RLyen0L8edXnAhh1HdMn77Tkzv0feUKYDkqOPCNmCWuhG2rqZ1Kon6Ks7sqURdbf2PvJh4twdwqov28HWArwgvkZiBFeh1ZCpQA32KO78uJKIR5A5DF7k84kT+odG6/y8ddkfNwbsDzEZWpGMs0VeqGPHPuDO941t2M6BzAsDb6Nm764T6I4zXKfUfpMetvXETK6FRl8tbcHzACT/EXb1o/Q5eYipQnl7R1Zy5ylMEnaFys74oFpvxm9s21BG+qbS5dAVeaphQG6uQONLLjDQ7STEzPXoG8DKjXjM7BX55ci4zsu7y2LMPeA6Z1YRc9V9OWaMoYdn1TOr3svvAMxT1GM39N6qsQNTKXmlI5qkmHSleCJOgC4WOARo7MVqu13mWMGh4bVOjF0u+zle0ZPnjuF/QhlJQ7Jldw0ZQKsZ+2cm8pG2X+N7BXxlYpe3KRKuH9fhmI4REOvDK07ALnMJhLrnR0UzTVjq9jiEKfdrpKZiQLDhuTxDoiRUkgSC4aQkxkPIff9pluOnqNMXvwtRzQpDIUniuBInFaLUEj+hpAFLNEEXVblhy5v9A==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: pocket-id-oidc-secrets
      namespace: argocd
    type: Opaque
